version: '2'
services:
  zookeeper:
    image: hyperledger/fabric-zookeeper

  orderer:
    image: hyperledger/fabric-testenv-orderer
    environment:
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISPROFILE=SampleInsecureKafka
    ports:
      - '7050'
    depends_on:
      - zookeeper
      - kafka

  kafka:
    image: hyperledger/fabric-kafka
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    depends_on:
      - zookeeper
